services:
  db:
    image: mysql:8.0.25
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_SCHEMA: ${MYSQL_DB_SCHEMA}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
#      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5