spring:
  main:
    web-application-type: none
  application:
    name: Datastore
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: ${MYSQL_DB_SCHEMA}
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholders:
      schema: ${MYSQL_DB_SCHEMA}
      default-schema: ${MYSQL_DB_SCHEMA}
      sql-migration-prefix: V
      sql-migration-separator: __
      sql-migration-suffixes: .sql
      datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_SCHEMA}?createDatabaseIfNotExist=true
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
datastore:
  view-path: /view/components/